"""Persian strings for the dashboard (hosted users). Key = the English text in the template."""

FA: dict[str, str] = {
    # nav + common
    "Status": "وضعیت",
    "Settings": "تنظیمات",
    "Contacts": "مخاطب\u200cها",
    "Prompts": "پرامپت\u200cها",
    "Drafts": "پیش\u200cنویس\u200cها",
    "Log out": "خروج",
    "Log in": "ورود",
    "Save": "ذخیره",
    "Send": "ارسال",
    "Skip": "رد کردن",
    "Add": "افزودن",
    "Remove": "حذف",
    "Search": "جستجو",
    "on": "روشن",
    "off": "خاموش",
    "On": "روشن",
    "Off": "خاموش",
    "paused": "متوقف",
    "default": "پیش\u200cفرض",
    "Default": "پیش\u200cفرض",
    "to": "تا",
    # status
    "Bot": "ربات",
    "up": "فعال از",
    "model": "مدل",
    "Auto-reply:": "پاسخ خودکار:",
    "Approval mode:": "حالت تأیید:",
    "Inner-circle gate:": "قفل دایره نزدیک:",
    "change": "تغییر",
    "OpenRouter credit:": "اعتبار OpenRouter:",
    "unavailable": "در دسترس نیست",
    "no limit, used": "بدون سقف، مصرف",
    "left": "باقی\u200cمانده",
    "Business connection": "اتصال بیزینس",
    "enabled": "فعال",
    "disabled": "غیرفعال",
    "missing rights:": "دسترسی\u200cهای کم:",
    "reply": "پاسخ دادن",
    "read messages": "خواندن پیام\u200cها",
    "Telegram → Settings → Business → Chatbots": "تلگرام ← تنظیمات ← Business ← Chatbots",
    "Not connected. In Telegram open Settings → Business → Chatbots and add":
        "وصل نیست. در تلگرام به تنظیمات ← Business ← Chatbots برو و این ربات را اضافه کن:",
    "Activity": "فعالیت",
    "replies today": "پاسخ امروز",
    "this week": "این هفته",
    "chats": "گفتگو",
    "drafts waiting": "پیش\u200cنویس در انتظار",
    "When": "زمان",
    "Chat": "گفتگو",
    "Reply": "پاسخ",
    "No bot replies yet.": "هنوز پاسخی از ربات نیست.",
    # settings
    "The token, API key or owner change needs a restart. Under pm2 the bot is back in a few seconds; without pm2 it stays stopped.":
        "تغییر توکن، کلید API یا مالک نیاز به راه\u200cاندازی دوباره دارد. با pm2 ربات چند ثانیه بعد برمی\u200cگردد؛ بدون pm2 خاموش می\u200cماند.",
    "Restart now": "همین حالا راه\u200cاندازی دوباره",
    "Live": "زنده",
    "applies to the next message, same as the /commands": "از پیام بعدی اعمال می\u200cشود، مثل دستورهای /",
    "Pause all auto-replies": "توقف همه پاسخ\u200cهای خودکار",
    "Approval mode: every reply waits for you in Drafts": "حالت تأیید: هر پاسخ در پیش\u200cنویس\u200cها منتظر تو می\u200cماند",
    "Inner-circle gate: hold emotional, long or after-silence messages from gf, family, bff and close friends":
        "قفل دایره نزدیک: پیام\u200cهای احساسی، بلند یا بعد از سکوت طولانی از دوست\u200cدختر/پسر، خانواده و دوستان نزدیک نگه داشته می\u200cشود",
    "Voice transcription": "تبدیل ویس به متن",
    "Quiet hours": "ساعت سکوت",
    "both empty = none": "هر دو خالی = بدون سکوت",
    "Reply delay (s)": "تأخیر پاسخ (ثانیه)",
    "Away-mode delay (s)": "تأخیر حالت دور از دسترس (ثانیه)",
    "Owner-active cooldown (s)": "وقفه بعد از فعالیت مالک (ثانیه)",
    "Config": "پیکربندی",
    "saved to .env (the old one is backed up)": "در فایل .env ذخیره می\u200cشود (از قبلی نسخه پشتیبان گرفته می\u200cشود)",
    "Reply model": "مدل پاسخ",
    "Extractor model": "مدل استخراج",
    "Voice model": "مدل ویس",
    "Your first name": "نام کوچک تو",
    "History turns per reply": "تعداد پیام\u200cهای تاریخچه برای هر پاسخ",
    "Needs a restart": "نیاز به راه\u200cاندازی دوباره",
    "Telegram bot token": "توکن ربات تلگرام",
    "OpenRouter API key": "کلید API ی OpenRouter",
    "Owner user id": "شناسه کاربری مالک",
    "blank keeps it": "خالی = بدون تغییر",
    "Restarting…": "در حال راه\u200cاندازی دوباره…",
    "Under pm2 the bot comes back in a few seconds and this page reloads. Without pm2 the bot is now stopped; start it again by hand.":
        "با pm2 ربات چند ثانیه بعد برمی\u200cگردد و این صفحه دوباره بارگذاری می\u200cشود. بدون pm2 ربات الان خاموش است؛ خودت دوباره روشنش کن.",
    # contacts
    "name, @username or chat id": "نام، @نام\u200cکاربری یا شناسه گفتگو",
    "Name": "نام",
    "Relationship": "نسبت",
    "Last message": "آخرین پیام",
    "Messages": "پیام\u200cها",
    "untagged": "بدون برچسب",
    "No chats yet.": "هنوز گفتگویی نیست.",
    "Profile": "پروفایل",
    "Nickname": "لقب",
    "Pause auto-replies in this chat": "توقف پاسخ خودکار در این گفتگو",
    "Note (added to the prompt for this chat)": "یادداشت (به پرامپت این گفتگو اضافه می\u200cشود)",
    "Prompt file": "فایل پرامپت",
    "Empty deletes the file.": "خالی بگذاری فایل پاک می\u200cشود.",
    "Memory": "حافظه",
    "No memories yet.": "هنوز چیزی در حافظه نیست.",
    "new memory": "خاطره جدید",
    "Extract from recent messages now": "همین حالا از پیام\u200cهای اخیر استخراج کن",
    "Style fingerprint": "اثر انگشت سبک",
    "Last messages": "آخرین پیام\u200cها",
    "them": "او",
    "you": "تو",
    "No messages.": "پیامی نیست.",
    # drafts
    "expires": "انقضا",
    "Edit the text before sending if you like.": "اگر خواستی قبل از ارسال متن را ویرایش کن.",
    "No drafts waiting. Approval mode and the inner-circle gate put replies here.":
        "پیش\u200cنویسی در انتظار نیست. حالت تأیید و قفل دایره نزدیک پاسخ\u200cها را اینجا می\u200cگذارند.",
    # login
    "to your bot in Telegram to get a one-time login link.": "را در تلگرام برای ربات خودت بفرست تا لینک ورود یک\u200cبارمصرف بگیری.",
    "token from the link": "توکن داخل لینک",
    # prompts
    "About me goes into every reply. Each persona applies to contacts tagged with that relationship. Write":
        "«درباره من» در هر پاسخ استفاده می\u200cشود. هر پرسونا برای مخاطبانی است که آن نسبت را دارند. به جای نام خودت بنویس:",
    "where your name goes.": "در جایی که اسمت می\u200cآید.",
    "Empty deletes your file, so the example applies again.": "خالی بگذاری فایل تو پاک می\u200cشود و دوباره نمونه اعمال می\u200cشود.",
    "Empty deletes your file (template: prompts/about_me.example.txt).": "خالی بگذاری فایل تو پاک می\u200cشود (الگو: prompts/about_me.example.txt).",
    # flash messages
    "Nothing changed.": "چیزی تغییر نکرد.",
    "Saved and applied.": "ذخیره و اعمال شد.",
    "Saved. Applies to the next message.": "ذخیره شد. از پیام بعدی اعمال می\u200cشود.",
    "Saved. Restart to apply the token, key or owner change.": "ذخیره شد. برای اعمال تغییر توکن، کلید یا مالک راه\u200cاندازی دوباره لازم است.",
    "Quiet hours need both a start and an end time.": "ساعت سکوت هم شروع می\u200cخواهد هم پایان.",
    "Unknown voice setting.": "تنظیم ویس نامعتبر است.",
    "must be a whole number (blank = default).": "باید عدد صحیح باشد (خالی = پیش\u200cفرض).",
    "can't be empty.": "نباید خالی باشد.",
    "must be a positive whole number.": "باید عدد صحیح مثبت باشد.",
    "History turns must be between 1 and 100.": "تعداد پیام\u200cهای تاریخچه باید بین ۱ تا ۱۰۰ باشد.",
    "Unknown model id:": "شناسه مدل نامعتبر:",
    "Couldn't reach the service to check it; nothing saved.": "به سرویس وصل نشدم تا بررسی کنم؛ چیزی ذخیره نشد.",
    "Couldn't write .env; nothing applied.": "نتوانستم .env را بنویسم؛ چیزی اعمال نشد.",
    "No active business connection yet. Connect the bot in Telegram first.":
        "هنوز اتصال بیزینس فعالی نیست. اول ربات را در تلگرام وصل کن.",
    "Unknown relationship.": "نسبت نامعتبر است.",
    "Saved.": "ذخیره شد.",
    "Prompt file saved.": "فایل پرامپت ذخیره شد.",
    "Pick a kind and write the memory.": "یک نوع انتخاب کن و خاطره را بنویس.",
    "Memory added.": "خاطره اضافه شد.",
    "Memory removed.": "خاطره حذف شد.",
    "Extraction queued. The memory worker runs it within ~15s (it skips chats with few new messages).":
        "استخراج در صف قرار گرفت. حافظه\u200cساز تا حدود ۱۵ ثانیه دیگر اجرایش می\u200cکند (گفتگوهای با پیام جدید کم را رد می\u200cکند).",
    "Saved:": "ذخیره شد:",
    "Pending reply not found:": "پاسخ در انتظار پیدا نشد:",
    "The reply is empty.": "پاسخ خالی است.",
    "Unknown action.": "عمل نامعتبر است.",
    "That link is invalid, used or expired. Send /dashboard to your bot for a new one.":
        "این لینک نامعتبر است، قبلاً استفاده شده یا منقضی شده. برای لینک جدید /dashboard را برای ربات بفرست.",
}
