"""Persian strings for the dashboard (hosted users). Key = the English text in the template."""

FA: dict[str, str] = {
    # nav + common
    "Status": "وضعیت",
    "Settings": "تنظیمات",
    "Contacts": "مخاطب\u200cها",
    "Log out": "خروج",
    "Log in": "ورود",
    "Save": "ذخیره",
    "Skip": "رد کردن",
    "Add": "افزودن",
    "Search": "جستجو",
    "on": "روشن",
    "off": "خاموش",
    "On": "روشن",
    "Off": "خاموش",
    "paused": "متوقف",
    "default": "پیش\u200cفرض",
    "Default": "پیش\u200cفرض",
    # status
    "tg-secretary": "منشی تلگرام",
    "Your account": "حساب کاربری",
    "Sections": "بخش\u200cها",
    "Bot": "ربات",
    "model": "مدل",
    "running for": "روشن از",
    "d": "روز",
    "h": "ساعت",
    "m": "دقیقه",
    "unavailable": "فعلاً معلوم نیست",
    "no limit, used": "بدون سقف، مصرف\u200cشده",
    "left": "مانده",
    "reply": "جواب دادن به پیام\u200cها",
    "read messages": "خواندن پیام\u200cها",
    "Your secretary is on and answering.": "منشی\u200cات روشن است و جواب می\u200cدهد.",
    "Every reply waits for your OK in Drafts before it goes out.":
        "هر جواب اول در «منتظر تأیید تو» می\u200cماند، بعد فرستاده می\u200cشود.",
    "When someone messages you and you don't answer, it replies for you.":
        "وقتی کسی بهت پیام بدهد و خودت جواب ندهی، منشی به جایت جواب می\u200cدهد.",
    "Your secretary is paused.": "منشی\u200cات خاموش است.",
    "Nothing is sent for you until you turn it back on.": "تا دوباره روشنش نکنی، هیچ جوابی از طرف تو فرستاده نمی\u200cشود.",
    "Turn it back on in Settings": "روشن کردن در تنظیمات",
    "Your credit has run out.": "اعتبارت تمام شده.",
    "Replies stop until you add credit.": "تا اعتبار اضافه نکنی، منشی جواب نمی\u200cدهد.",
    "Add credit": "افزایش اعتبار",
    "Your secretary can't answer yet.": "منشی\u200cات هنوز نمی\u200cتواند جواب بدهد.",
    "Connect it to your Telegram account:": "این چند قدم را در تلگرام انجام بده تا وصل شود:",
    "Open Telegram and go to Settings.": "تلگرام را باز کن و برو به تنظیمات (Settings).",
    "Open Chat Automation (on some phones: Telegram Business, then Chatbots).":
        "بخش Chat Automation را باز کن (در بعضی نسخه\u200cها: Telegram Business و بعد Chatbots).",
    "Enter this bot's username and add it:": "نام کاربری این ربات را وارد کن و اضافه\u200cاش کن:",
    "Turn on permission to reply to messages, then come back here.":
        "اجازه جواب دادن به پیام\u200cها را روشن کن و برگرد همین\u200cجا.",
    "The bot is connected but switched off in Telegram:": "ربات وصل است ولی در تلگرام خاموش شده:",
    "Select": "ربات",
    "and turn it on.": "را انتخاب کن و روشنش کن.",
    "The bot is connected but isn't allowed to send replies:": "ربات وصل است ولی اجازه فرستادن جواب ندارد:",
    "and turn on permission to reply to messages.": "را انتخاب کن و اجازه جواب دادن به پیام\u200cها را روشن کن.",
    "Missing permission in Telegram:": "این اجازه در تلگرام خاموش است:",
    "Turn it on under Chat Automation for the best results.": "برای کار بهتر، در Chat Automation روشنش کن.",
    "replies are waiting for your OK": "جواب منتظر تأیید توست",
    "Nothing is sent until you check them.": "تا خودت نگاهشان نکنی، فرستاده نمی\u200cشوند.",
    "Review drafts": "دیدنشان",
    "Credit left": "اعتبار باقی\u200cمانده",
    "Replies today": "جواب\u200cهای امروز",
    "Replies this week": "جواب\u200cهای این هفته",
    "People who messaged": "آدم\u200cهایی که پیام دادند",
    "Latest replies": "آخرین جواب\u200cها",
    "No replies sent yet. They'll show up here once your secretary answers someone.":
        "هنوز جوابی فرستاده نشده. وقتی منشی به کسی جواب بدهد، اینجا می\u200cبینی\u200cاش.",
    "Technical details": "جزئیات فنی",
    # settings
    "The token, API key or owner change needs a restart. Under pm2 the bot is back in a few seconds; without pm2 it stays stopped.":
        "تغییر توکن، کلید API یا مالک نیاز به راه\u200cاندازی دوباره دارد. با pm2 ربات چند ثانیه بعد برمی\u200cگردد؛ بدون pm2 خاموش می\u200cماند.",
    "Restart now": "همین حالا راه\u200cاندازی دوباره",
    "Advanced settings": "تنظیمات پیشرفته",
    "Save changes": "ذخیره تغییرات",
    "Replying": "پاسخ دادن",
    "When the secretary answers for you.": "منشی کی به جای تو جواب بدهد.",
    "Pause all auto-replies": "توقف همه پاسخ\u200cهای خودکار",
    "Nothing is sent until you turn this off.": "تا خاموشش نکنی هیچ پاسخی فرستاده نمی\u200cشود.",
    "Ask me before sending": "قبل از ارسال از من بپرس",
    "Every reply waits for you in Drafts.": "هر پاسخ در «منتظر تأیید تو» می\u200cماند.",
    "Hold sensitive messages from close people": "پیام\u200cهای حساس آدم\u200cهای نزدیک را نگه دار",
    "Emotional, long or after-a-silence messages from your partner, family and close friends wait for you in Drafts.":
        "پیام\u200cهای احساسی، بلند یا بعد از مدتی سکوت از پارتنر، خانواده و دوستان نزدیک در «منتظر تأیید تو» می\u200cمانند.",
    "Timing": "زمان\u200cبندی",
    "How soon replies go out.": "پاسخ\u200cها چه زمانی فرستاده شوند.",
    "Wait before replying": "صبر قبل از پاسخ",
    "Gives you time to answer yourself first. Leave empty for the default.":
        "فرصت می\u200cدهد اول خودت جواب بدهی. خالی بگذاری، مقدار پیش\u200cفرض اعمال می\u200cشود.",
    "seconds": "ثانیه",
    "Quiet hours": "ساعت سکوت",
    "Leave both empty to reply at any hour.": "هر دو را خالی بگذاری، در هر ساعتی جواب می\u200cدهد.",
    "Don't reply between": "جواب نده از ساعت",
    "and": "تا",
    "Quiet hours start": "شروع ساعت سکوت",
    "Quiet hours end": "پایان ساعت سکوت",
    "Voice messages": "پیام\u200cهای صوتی",
    "Voice messages are turned into text, then answered like any other message.":
        "ویس\u200cها اول به متن تبدیل می\u200cشوند و بعد مثل هر پیام دیگری جواب می\u200cگیرند.",
    "Answer voice messages": "به ویس\u200cها جواب بده",
    "About you": "درباره تو",
    "The name the secretary uses for you in replies.": "اسمی که منشی در پاسخ\u200cها برای تو به کار می\u200cبرد.",
    "Technical": "تنظیمات فنی",
    "For people who know what these do.": "برای کسانی که می\u200cدانند هر کدام چه می\u200cکند.",
    "Default follows the server config.": "پیش\u200cفرض از تنظیمات سرور پیروی می\u200cکند.",
    "Voice transcription": "تبدیل ویس به متن",
    "Reply delay (s)": "تأخیر پاسخ (ثانیه)",
    "Away-mode delay (s)": "تأخیر حالت دور از دسترس (ثانیه)",
    "Owner-active cooldown (s)": "وقفه بعد از فعالیت مالک (ثانیه)",
    "Models": "مدل\u200cها",
    "OpenRouter model ids. Saved to .env (the old one is backed up).":
        "شناسه مدل\u200cهای هوش مصنوعی. با ذخیره، از تنظیمات قبلی نسخه پشتیبان گرفته می\u200cشود.",
    "These take effect after a restart.": "این\u200cها بعد از راه\u200cاندازی دوباره اعمال می\u200cشوند.",
    "Reply model": "مدل پاسخ",
    "Extractor model": "مدل استخراج",
    "Voice model": "مدل ویس",
    "Your first name": "نام کوچک تو",
    "History turns per reply": "تعداد پیام\u200cهای تاریخچه برای هر پاسخ",
    "Needs a restart": "نیاز به راه\u200cاندازی دوباره",
    "Telegram bot token": "توکن ربات تلگرام",
    "OpenRouter API key": "کلید API ی OpenRouter",
    "Owner user id": "شناسه کاربری مالک",
    "blank keeps it": "خالی = بدون تغییر",
    "Restarting…": "در حال راه\u200cاندازی دوباره…",
    "Under pm2 the bot comes back in a few seconds and this page reloads. Without pm2 the bot is now stopped; start it again by hand.":
        "با pm2 ربات چند ثانیه بعد برمی\u200cگردد و این صفحه دوباره بارگذاری می\u200cشود. بدون pm2 ربات الان خاموش است؛ خودت دوباره روشنش کن.",
    # contacts
    "name, @username or chat id": "نام، @نام\u200cکاربری یا شناسه گفتگو",
    "Name": "نام",
    "Messages": "پیام\u200cها",
    "untagged": "بدون برچسب",
    "No chats yet.": "هنوز گفتگویی نیست.",
    "Profile": "پروفایل",
    "Note (added to the prompt for this chat)": "یادداشت (به پرامپت این گفتگو اضافه می\u200cشود)",
    "Prompt file": "فایل پرامپت",
    "Empty deletes the file.": "خالی بگذاری فایل پاک می\u200cشود.",
    "Memory": "حافظه",
    "No memories yet.": "هنوز چیزی در حافظه نیست.",
    "new memory": "خاطره جدید",
    "Extract from recent messages now": "همین حالا از پیام\u200cهای اخیر استخراج کن",
    "Style fingerprint": "اثر انگشت سبک",
    "Last messages": "آخرین پیام\u200cها",
    "No messages.": "پیامی نیست.",
    # drafts
    "expires": "انقضا",
    "Edit the text before sending if you like.": "اگر خواستی قبل از ارسال متن را ویرایش کن.",
    "No drafts waiting. Approval mode and the inner-circle gate put replies here.":
        "چیزی منتظر تأیید تو نیست. حالت تأیید و قفل دایره نزدیک پاسخ\u200cها را اینجا می\u200cگذارند.",
    # login
    "to your bot in Telegram to get a one-time login link.": "را در تلگرام برای ربات خودت بفرست تا لینک ورود یک\u200cبارمصرف بگیری.",
    "token from the link": "توکن داخل لینک",
    # prompts
    "About me goes into every reply. Each persona applies to contacts tagged with that relationship. Write":
        "«درباره من» در هر پاسخ استفاده می\u200cشود. هر پرسونا برای مخاطبانی است که آن نسبت را دارند. به جای نام خودت بنویس:",
    "where your name goes.": "در جایی که اسمت می\u200cآید.",
    "Empty deletes your file, so the example applies again.": "خالی بگذاری فایل تو پاک می\u200cشود و دوباره نمونه اعمال می\u200cشود.",
    "Empty deletes your file (template: prompts/about_me.example.txt).": "خالی بگذاری فایل تو پاک می\u200cشود (الگو: prompts/about_me.example.txt).",
    # flash messages
    "Nothing changed.": "چیزی تغییر نکرد.",
    "Saved and applied.": "ذخیره و اعمال شد.",
    "Saved. Applies to the next message.": "ذخیره شد. از پیام بعدی اعمال می\u200cشود.",
    "Saved. Restart to apply the token, key or owner change.": "ذخیره شد. برای اعمال تغییر توکن، کلید یا مالک راه\u200cاندازی دوباره لازم است.",
    "Quiet hours need both a start and an end time.": "ساعت سکوت هم شروع می\u200cخواهد هم پایان.",
    "Unknown voice setting.": "تنظیم ویس نامعتبر است.",
    "must be a whole number (blank = default).": "باید عدد صحیح باشد (خالی = پیش\u200cفرض).",
    "can't be empty.": "نباید خالی باشد.",
    "must be a positive whole number.": "باید عدد صحیح مثبت باشد.",
    "History turns must be between 1 and 100.": "تعداد پیام\u200cهای تاریخچه باید بین ۱ تا ۱۰۰ باشد.",
    "Unknown model id:": "شناسه مدل نامعتبر:",
    "Couldn't reach the service to check it; nothing saved.": "به سرویس وصل نشدم تا بررسی کنم؛ چیزی ذخیره نشد.",
    "Couldn't write .env; nothing applied.": "نتوانستم .env را بنویسم؛ چیزی اعمال نشد.",
    "No active business connection yet. Connect the bot in Telegram first.":
        "هنوز اتصال بیزینس فعالی نیست. اول ربات را در تلگرام وصل کن.",
    "Prompt file saved.": "فایل پرامپت ذخیره شد.",
    "Extraction queued. The memory worker runs it within ~15s (it skips chats with few new messages).":
        "استخراج در صف قرار گرفت. حافظه\u200cساز تا حدود ۱۵ ثانیه دیگر اجرایش می\u200cکند (گفتگوهای با پیام جدید کم را رد می\u200cکند).",
    "Saved:": "ذخیره شد:",
    "Pending reply not found:": "پاسخ در انتظار پیدا نشد:",
    "That link is invalid, used or expired. Send /dashboard to your bot for a new one.":
        "این لینک نامعتبر است، قبلاً استفاده شده یا منقضی شده. برای لینک جدید /dashboard را برای ربات بفرست.",
    # contacts / contact / prompts / drafts (agent B). Overrides earlier entries with the same key.
    "Prompts": "شخصیت و لحن",
    "Drafts": "منتظر تأیید تو",
    # relationship labels (contacts.RELATIONSHIPS)
    "Partner": "همسر / پارتنر",
    "Family": "خانواده",
    "Best friend": "بهترین دوست",
    "Close friend": "دوست صمیمی",
    "Friend": "دوست",
    "Work": "کاری / همکار",
    "Acquaintance": "آشنا",
    "Not set": "مشخص نشده",
    "About me": "درباره من",
    # memory kinds (contacts.MEMORY_KINDS)
    "Fact": "واقعیت",
    "Likes and dislikes": "سلیقه",
    "Event": "اتفاق",
    "Promise": "قول و قرار",
    "Inside joke": "شوخی خودمانی",
    "Unfinished topic": "حرف نیمه\u200cتمام",
    # contacts list
    "Everyone who has messaged you. Open a person to tell the secretary who they are and how to talk to them.":
        "همه کسانی که به تو پیام داده\u200cاند. روی هر نفر بزن تا به منشی بگویی کیست و چطور با او حرف بزند.",
    "Search contacts": "جستجوی مخاطب\u200cها",
    "Search by name or @username": "جستجو با اسم یا @نام\u200cکاربری",
    "Show everyone": "نمایش همه",
    "Auto-reply off": "پاسخ خودکار خاموش",
    "Last message": "آخرین پیام",
    "messages": "پیام",
    "No one matches your search.": "کسی با این جستجو پیدا نشد.",
    "No one has messaged you yet.": "هنوز کسی به تو پیام نداده.",
    "When someone writes to you on Telegram, they show up here and you can set how the secretary talks to them.":
        "وقتی کسی در تلگرام به تو پیام بدهد، اینجا می\u200cآید و می\u200cتوانی تعیین کنی منشی چطور با او حرف بزند.",
    # contact page
    "Back to contacts": "برگشت به مخاطب\u200cها",
    "Auto-reply is off for this person. The secretary won't answer them until you turn it back on.":
        "پاسخ خودکار برای این نفر خاموش است. تا دوباره روشنش نکنی، منشی جوابش را نمی\u200cدهد.",
    "Who is this?": "این آدم کیست؟",
    "Relationship": "نسبت با تو",
    "The secretary talks to each group in its own way. You set how on the Prompts page.":
        "منشی با هر گروه به شیوه خودش حرف می\u200cزند. این شیوه را در صفحه «شخصیت و لحن» تعیین می\u200cکنی.",
    "Nickname": "اسمی که صدایش می\u200cکنی",
    "The name you use for them. Shown in this dashboard.": "اسمی که خودت برایش به کار می\u200cبری. در همین داشبورد نشان داده می\u200cشود.",
    "Pause auto-replies in this chat": "خاموش کردن پاسخ خودکار برای این نفر",
    "The secretary stays quiet with this person; you answer them yourself.":
        "منشی با این نفر حرفی نمی\u200cزند و خودت جوابش را می\u200cدهی.",
    "A short note for the secretary": "یک یادداشت کوتاه برای منشی",
    "Anything to keep in mind with this person. For example: we work together, keep it polite.":
        "هر چیزی که منشی باید درباره این نفر در نظر بگیرد. مثلاً: همکاریم، مؤدبانه حرف بزن.",
    "What the secretary knows about them": "چیزهایی که منشی درباره\u200cاش می\u200cداند",
    "It picks up facts from your chats and uses them in replies. Remove anything wrong, or add something yourself.":
        "منشی از گفتگوهایتان نکته برمی\u200cدارد و در جواب\u200cها از آن\u200cها استفاده می\u200cکند. هر چیزی که غلط است را حذف کن، یا خودت چیزی اضافه کن.",
    "Nothing yet. It fills in as you chat.": "هنوز چیزی نیست. کم\u200cکم با گفتگوها پر می\u200cشود.",
    "Kind": "نوع",
    "New fact": "نکته جدید",
    "For example: has a cat named Mishi": "مثلاً: یک گربه به اسم میشی دارد",
    "Learn from recent messages now": "همین الان از پیام\u200cهای اخیر یاد بگیر",
    "It does this on its own every so often. Use it if you want an update right away.":
        "منشی هر چند وقت یک بار خودش این کار را می\u200cکند. اگر همین الان به\u200cروزرسانی می\u200cخواهی، این را بزن.",
    "How you usually write to them": "تو معمولاً چطور برایش می\u200cنویسی",
    "Learned from your own messages, so replies sound like you.": "از پیام\u200cهای خودت یاد گرفته شده تا جواب\u200cها شبیه خودت باشد.",
    "Usual message length": "طول معمول پیام",
    "characters": "حرف",
    "Tone": "لحن",
    "casual": "خودمانی",
    "warm": "گرم و صمیمی",
    "formal": "رسمی",
    "Emoji": "ایموجی",
    "none": "هیچ",
    "light": "کم",
    "heavy": "زیاد",
    "Languages": "زبان\u200cها",
    "English": "انگلیسی",
    "Persian": "فارسی",
    "Pet names": "اسم\u200cهای خودمانی",
    "Usual opening": "شروع همیشگی",
    "Usual closing": "پایان همیشگی",
    "Detailed instructions for this person": "دستورالعمل مخصوص این نفر",
    "Optional. Write in plain words how the secretary should talk to them and what to avoid. This is added on top of the group's style from the Prompts page.":
        "اختیاری. به زبان ساده بنویس منشی چطور با او حرف بزند و از چه چیزهایی دوری کند. این روی لحن گروهش (از صفحه «شخصیت و لحن») اضافه می\u200cشود.",
    "Leave it empty to remove these instructions.": "اگر خالی\u200cاش بگذاری و ذخیره کنی، این دستورالعمل حذف می\u200cشود.",
    "Recent conversation": "گفتگوی اخیر",
    "them": "او",
    "you": "تو",
    "No messages yet.": "هنوز پیامی نیست.",
    "Remove": "حذف",
    # prompts page
    "Here you tell the secretary how to talk. Write in plain words, the way you'd explain it to a friend who answers for you.":
        "اینجا به منشی می\u200cگویی چطور حرف بزند. ساده بنویس، همان\u200cطور که برای دوستی توضیح می\u200cدهی که قرار است به جای تو جواب بدهد.",
    "\"About me\" is used in every reply. Each of the other boxes is for one group of people: whoever you mark as that relationship on their contact page gets that style.":
        "«درباره من» در همه جواب\u200cها استفاده می\u200cشود. هر کدام از بقیه بخش\u200cها برای یک گروه از آدم\u200cهاست: هر کس را در صفحه\u200cاش با آن نسبت مشخص کنی، با همان لحن جواب می\u200cگیرد.",
    "Wherever you write": "هر جا بنویسی",
    ", your first name goes in its place.": "، اسم کوچکت به جایش قرار می\u200cگیرد.",
    "Your own text": "نوشته خودت",
    "Ready-made sample. Saving makes it yours.": "نمونه آماده. با ذخیره، مال خودت می\u200cشود.",
    "Built-in default. Saving makes it yours.": "متن پیش\u200cفرض. با ذخیره، مال خودت می\u200cشود.",
    "Empty": "خالی",
    "Facts about you that any reply may need: what you do, where you live, what you're busy with these days.":
        "چیزهایی درباره خودت که هر جوابی ممکن است لازم داشته باشد: چه کار می\u200cکنی، کجا زندگی می\u200cکنی، این روزها مشغول چه هستی.",
    "How to talk to people you haven't put in a group yet.": "منشی با کسانی که هنوز در گروهی نگذاشته\u200cای چطور حرف بزند.",
    "How to talk to people you marked as:": "منشی با کسانی که این\u200cطور مشخص کرده\u200cای چطور حرف بزند:",
    "Leave it empty and save to go back to the ready-made sample.": "اگر خالی\u200cاش بگذاری و ذخیره کنی، به نمونه آماده برمی\u200cگردد.",
    "Leave it empty and save to remove it.": "اگر خالی\u200cاش بگذاری و ذخیره کنی، حذف می\u200cشود.",
    # drafts page
    "These replies wait for your OK. Change the text if you like, then send it or skip it.":
        "این جواب\u200cها منتظر تأیید تو هستند. اگر خواستی متن را عوض کن، بعد بفرست یا نفرست.",
    "Waits until": "منتظر می\u200cماند تا",
    "They wrote": "پیام او",
    "Suggested reply": "جواب پیشنهادی",
    "Send": "ارسال",
    "Don't send": "نفرست",
    "Nothing waiting for you.": "چیزی منتظر تأیید تو نیست.",
    "Replies show up here when you've asked to approve them first, or when a close person sends something sensitive. You can change both in Settings.":
        "جواب\u200cها وقتی اینجا می\u200cآیند که خواسته باشی اول خودت تأییدشان کنی، یا یکی از آدم\u200cهای نزدیکت پیام حساسی بفرستد. هر دو را در «تنظیمات» می\u200cتوانی عوض کنی.",
    # flash messages (contacts.py / drafts.py)
    "Saved.": "ذخیره شد.",
    "Instructions saved.": "دستورالعمل ذخیره شد.",
    "Pick a kind and write the memory.": "یک نوع انتخاب کن و نکته را بنویس.",
    "Memory added.": "نکته اضافه شد.",
    "Memory removed.": "نکته حذف شد.",
    "Reading the recent messages now. New facts show up here in about a minute (nothing changes if there's little new).":
        "منشی دارد پیام\u200cهای اخیر را می\u200cخواند. نکته\u200cهای تازه تا حدود یک دقیقه دیگر اینجا می\u200cآیند (اگر پیام تازه کم باشد، چیزی عوض نمی\u200cشود).",
    "Unknown relationship.": "این نسبت شناخته\u200cشده نیست.",
    "Sent.": "فرستاده شد.",
    "Skipped. Nothing was sent.": "باشه، چیزی فرستاده نشد.",
    "Couldn't send it. Try again in a moment.": "نشد بفرستم. چند لحظه بعد دوباره امتحان کن.",
    "This reply was already handled or has expired.": "این جواب قبلاً بررسی شده یا وقتش گذشته.",
    "The reply is empty.": "جواب خالی است.",
    "Unknown action.": "این کار شناخته\u200cشده نیست.",
    # --- redesign: shell ---
    "Home": "خانه",
    "Waiting for you": "منتظر تو",
    "People": "آدم\u200cها",
    "Secretary's tone": "لحن منشی",
    "Introduce myself": "معرفی خودم",
    "Account and credit": "حساب و اعتبار",
    "Account": "حساب",
    # --- redesign: home, drafts, settings ---
    "Hi {name}": "سلام {name}",
    "It's on": "روشن است",
    "It's off": "خاموش است",
    "One step left": "یک قدم مانده",
    "Out of credit": "اعتبار تمام شده",
    "Your secretary is answering messages": "منشی جواب پیام\u200cها را می\u200cدهد",
    "Your secretary isn't answering for now": "منشی فعلاً جواب نمی\u200cدهد",
    "Your secretary is waiting for credit": "منشی منتظر اعتبار است",
    "Connect your secretary to Telegram": "منشی را به تلگرامت وصل کن",
    "Your secretary is switched off in Telegram": "منشی در تلگرام خاموش است",
    "Your secretary isn't allowed to reply": "منشی اجازه جواب دادن ندارد",
    "Every reply is shown to you first and goes out after you approve it.":
        "هر جواب اول به تو نشان داده می\u200cشود و بعد از تأیید تو فرستاده می\u200cشود.",
    "If you don't reply within {x}, the secretary answers in your voice.":
        "اگر تا {x} خودت جواب ندهی، منشی با لحن تو جواب می\u200cدهد.",
    "Until you switch it back on, nothing is sent for you.":
        "تا دوباره روشنش نکنی، هیچ جوابی از طرف تو فرستاده نمی\u200cشود.",
    "Until you add credit the secretary won't answer. Your settings stay as they are.":
        "تا اعتبار اضافه نکنی، منشی جواب نمی\u200cدهد. تنظیماتت سر جایش می\u200cماند.",
    "Three simple things in Telegram, about a minute:": "سه کار ساده در تلگرام، حدود یک دقیقه:",
    "Enter this name and turn on permission to reply to messages:":
        "این نام را وارد کن و اجازه «جواب دادن به پیام\u200cها» را روشن کن:",
    "Open Telegram": "باز کردن تلگرام",
    "Turn the secretary on or off": "روشن یا خاموش کردن منشی",
    "Saved": "ذخیره شد",
    "Couldn't save. Try again.": "ذخیره نشد. دوباره امتحان کن.",
    "Today": "امروز",
    "replies sent for you": "جواب به جای تو",
    "Credit": "اعتبار",
    "No spending limit": "بدون سقف",
    "{n} dollars used": "{n} دلار مصرف شده",
    "about {n} more replies": "حدود {n} جواب دیگر",
    "Used up": "تمام شده",
    "{r} of {t} dollars": "{r} از {t} دلار",
    "{n} people have no group yet": "{n} نفر هنوز گروه ندارند",
    "Tell me who they are so replies get the right tone.": "بگو کیستند تا منشی با لحن درست جوابشان را بدهد.",
    "Choose": "مشخص کن",
    "Connections": "اتصال\u200cها",
    "Waiting for your OK": "منتظر تأیید تو",
    "These replies aren't sent without your OK. Change the text if you like.":
        "این جواب\u200cها بدون نظر تو فرستاده نمی\u200cشوند. اگر خواستی متن را عوض کن.",
    "Waits {x} more": "تا {x} دیگر منتظر می\u200cماند",
    "You asked to approve every reply first": "خودت خواسته\u200cای هر جواب اول به تو نشان داده شود",
    "Sensitive message from {rel}": "پیام حساس از {rel}",
    "Held for your OK": "برای تأیید تو نگه داشته شد",
    "The secretary's suggested reply": "جواب پیشنهادی منشی",
    "Every change is saved the moment you make it.": "هر تغییری بدهی، همان لحظه ذخیره می\u200cشود.",
    "The secretary": "منشی",
    "Keep the secretary on": "منشی روشن باشد",
    "When it's off, no reply is sent on your behalf.": "خاموش که باشد، هیچ جوابی از طرف تو فرستاده نمی\u200cشود.",
    "Every reply waits in Waiting for you until you approve it.": "هر جواب اول در «منتظر تو» می\u200cماند تا تأییدش کنی.",
    "When it replies": "کی جواب بدهد",
    "How long should it wait for you to reply first?": "چقدر صبر کند تا خودت جواب بدهی؟",
    "If you reply in that time, the secretary stays quiet.": "اگر در این مدت خودت جواب بدهی، منشی ساکت می\u200cماند.",
    "10 seconds": "۱۰ ثانیه",
    "Half a minute": "نیم دقیقه",
    "2 minutes": "۲ دقیقه",
    "5 minutes": "۵ دقیقه",
    "For example at night while you sleep, the secretary doesn't reply either.":
        "مثلاً شب\u200cها که خوابی، منشی هم جواب نمی\u200cدهد.",
    "Don't reply from": "جواب نده از",
    "until": "تا",
    "Voice and name": "ویس و اسم",
    "Redo my introduction": "معرفی خودم را دوباره انجام بده",
    "About you, how you write, and what the secretary must never do.":
        "درباره تو، طرز نوشتنت، و کارهایی که منشی نباید بکند.",
    "Technical settings": "تنظیمات فنی",
    "Only if you know what each one does": "فقط اگر می\u200cدانی هر کدام چه می\u200cکند",
    # --- redesign: contacts, tone ---
    "Tell the secretary who each person is, so it answers them in the right tone.": "بگو هر کس کیست، تا منشی با لحن درست جوابش را بدهد.",
    "Filter": "فیلتر",
    "All": "همه",
    "No group yet": "بدون گروه",
    "Close ones": "نزدیکان",
    "At work": "کاری",
    "Secretary quiet": "منشی ساکت",
    "Secretary is quiet": "منشی ساکت است",
    "Set group": "گروه بده",
    "Could not save. Try again.": "ذخیره نشد. دوباره امتحان کن.",
    "The secretary has its own tone for each group.": "منشی با هر گروه لحن خودش را دارد.",
    "Secretary should not talk to this person": "منشی با این نفر حرف نزند",
    "You answer them yourself.": "خودت جوابش را می\u200cدهی.",
    "Done": "تمام",
    "Close": "بستن",
    "Edit": "ویرایش",
    "Warm and close. Sensitive messages come to you first.": "گرم و صمیمی؛ پیام حساس اول به تو نشان داده می\u200cشود",
    "Respectful and warm.": "محترمانه و گرم",
    "Very casual, with jokes.": "خیلی خودمانی، با شوخی",
    "Casual and close.": "خودمانی و صمیمی",
    "Friendly and short.": "دوستانه و کوتاه",
    "Polite and formal, makes no promises.": "مؤدب و رسمی، بدون قول دادن",
    "Polite and short.": "مؤدب و کوتاه",
    "Not sure yet, so it answers carefully and briefly.": "هنوز نمی\u200cدانم؛ محتاط و کوتاه جواب می\u200cدهد",
    "The secretary talks to each group in its own way. Pick the group and you see what it changes. You set the tone itself on the Tone page.": "منشی با هر گروه یک جور حرف می\u200cزند. گروه را که انتخاب کنی، زیرش می\u200cبینی چه چیزی عوض می\u200cشود. خود لحن را در صفحه «لحن منشی» تنظیم می\u200cکنی.",
    "Optional. Write in plain words how the secretary should talk to them and what to avoid. This is added on top of the group's style from the Tone page.": "اختیاری. ساده بنویس منشی چطور با این نفر حرف بزند و از چه چیزی دوری کند. این روی لحن گروه (از صفحه «لحن منشی») اضافه می\u200cشود.",
    "Tell the secretary how to talk to each group. You don't have to write anything, just pick.": "به منشی بگو با هر گروه چطور حرف بزند. لازم نیست چیزی بنویسی؛ فقط انتخاب کن.",
    "Used in every reply": "در همه جواب\u200cها استفاده می\u200cشود",
    "What you do, where you live, what keeps you busy these days. Any reply may need it.": "چه کار می\u200cکنی، کجا زندگی می\u200cکنی، این روزها چه چیزی سرت را شلوغ کرده. ممکن است هر جوابی به آن نیاز داشته باشد.",
    "Which group?": "برای کدام گروه؟",
    "Everyone else": "بقیه",
    "people": "نفر",
    "Formal": "رسمی",
    "Normal": "معمولی",
    "Casual": "خودمانی",
    "Reply length": "طول جواب",
    "Short": "کوتاه",
    "Longer": "مفصل",
    "None": "هیچ",
    "A few": "کم",
    "Lots": "زیاد",
    "Preview: if someone in this group writes": "پیش\u200cنمایش: اگر یکی از این گروه بنویسد",
    "Anything else?": "چیز دیگری هم هست؟",
    "optional": "اختیاری",
    "For example: call her dear, keep work out of it.": "مثلاً: «عزیزم» صدایش کن، درباره کار حرف نزن.",
    "Empty it and the ready-made sample comes back": "اگر خالی\u200cاش کنی، نمونه آماده برمی\u200cگردد",
    "Saves by itself": "خودکار ذخیره می\u200cشود",
    "Back to the suggested style": "برگرداندن به حالت پیشنهادی",
    "Back to the suggested style.": "به حالت پیشنهادی برگشت.",
    "The secretary should never…": "منشی هرگز نباید…",
    "Make promises": "قول بدهد",
    "Fix a firm meeting time": "قرار قطعی بگذارد",
    "Talk about money": "درباره پول حرف بزند",
    "Share my personal info": "اطلاعات شخصی من را بگوید",
    "Couldn't save that choice.": "این انتخاب ذخیره نشد.",
}
